name: pyFIRS
channels:
  - conda-forge
dependencies:
  - dask=1.0
  - geopandas=0.4
  - matplotlib=2.2
  - numpy=1.15
  - pandas=0.23
  - pdal=1.8
  - python-pdal=2.1
  - python>=3.6
  - rasterio=1.0
  - rasterstats=0.13
  - scikit-image=0.14
  - scikit-learn=0.20
  - seaborn=0.9
  - shapely=1.6
  - xarray
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - pip:
    - kubernetes
    - graphviz
