name: pyFIRS
channels:
  - conda-forge
dependencies:
  - dask
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - pdal
  - python-pdal
  - python>=3.6
  - rasterio
  - rasterstats
  - scikit-image
  - scikit-learn
  - seaborn
  - shapely
  - xarray
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - pip:
    - kubernetes
