name: pyFIRS
channels:
  - conda-forge
dependencies:
  - dask
  - dask-kubernetes
  - distributed
  - gcsfs
  - geopandas
  - graphviz
  - intake::intake-xarray
  - ipyleaflet
  - ipywidgets
  - jupyter
  - jupyter_client
  - jupyterlab_launcher
  - jupyterlab=0.35
  - lz4
  - matplotlib
  - nbconvert
  - nbserverproxy
  - nodejs
  - nomkl
  - notebook
  - numcodecs
  - numpy
  - pandas
  - pdal
  - python-blosc
  - python-pdal
  - python=3.6
  - rasterio
  - rasterstats
  - scikit-image
  - scikit-learn
  - seaborn
  - shapely
  - xarray
  - zarr
  - pip:
    - jupyterhub
    - kubernetes
    - nteract_on_jupyter
